create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list d_1_i/usp_rf_data_converter_0/inst/i_d_1_usp_rf_data_converter_0_0_bufg_gt_ctrl/clk_adc2]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {d_1_i/qp_do[0]} {d_1_i/qp_do[1]} {d_1_i/qp_do[2]} {d_1_i/qp_do[3]} {d_1_i/qp_do[4]} {d_1_i/qp_do[5]} {d_1_i/qp_do[6]} {d_1_i/qp_do[7]} {d_1_i/qp_do[8]} {d_1_i/qp_do[9]} {d_1_i/qp_do[10]} {d_1_i/qp_do[11]} {d_1_i/qp_do[12]} {d_1_i/qp_do[13]} {d_1_i/qp_do[14]} {d_1_i/qp_do[15]} {d_1_i/qp_do[16]} {d_1_i/qp_do[17]} {d_1_i/qp_do[18]} {d_1_i/qp_do[19]} {d_1_i/qp_do[20]} {d_1_i/qp_do[21]} {d_1_i/qp_do[22]} {d_1_i/qp_do[23]} {d_1_i/qp_do[24]} {d_1_i/qp_do[25]} {d_1_i/qp_do[26]} {d_1_i/qp_do[27]} {d_1_i/qp_do[28]} {d_1_i/qp_do[29]} {d_1_i/qp_do[30]} {d_1_i/qp_do[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {d_1_i/qp_val_do[0]} {d_1_i/qp_val_do[1]} {d_1_i/qp_val_do[2]} {d_1_i/qp_val_do[3]} {d_1_i/qp_val_do[4]} {d_1_i/qp_val_do[5]} {d_1_i/qp_val_do[6]} {d_1_i/qp_val_do[7]} {d_1_i/qp_val_do[8]} {d_1_i/qp_val_do[9]} {d_1_i/qp_val_do[10]} {d_1_i/qp_val_do[11]} {d_1_i/qp_val_do[12]} {d_1_i/qp_val_do[13]} {d_1_i/qp_val_do[14]} {d_1_i/qp_val_do[15]} {d_1_i/qp_val_do[16]} {d_1_i/qp_val_do[17]} {d_1_i/qp_val_do[18]} {d_1_i/qp_val_do[19]} {d_1_i/qp_val_do[20]} {d_1_i/qp_val_do[21]} {d_1_i/qp_val_do[22]} {d_1_i/qp_val_do[23]} {d_1_i/qp_val_do[24]} {d_1_i/qp_val_do[25]} {d_1_i/qp_val_do[26]} {d_1_i/qp_val_do[27]} {d_1_i/qp_val_do[28]} {d_1_i/qp_val_do[29]} {d_1_i/qp_val_do[30]} {d_1_i/qp_val_do[31]}]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_clk_adc2]
